name: 构建 Windows 和 Android 应用

on:
  push:
    tags:
      - 'v*'
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Version tag'
  #       required: true
  #       default: 'v0.0.1'

jobs:
  main:
    name: Release Windows App
    runs-on: windows-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 对比 Tag 和 pubspec.yaml 的 version
        run: |
          $tag = $env:GITHUB_REF
          if ($tag -like 'refs/tags/*') {
            $tag = $tag.Substring('refs/tags/'.Length)
          }
          $tag_version = $tag.Substring(1)
          echo "tagVersion: $tag_version"

          $pubspec_content = Get-Content pubspec.yaml
          $pubspec_version_line = $pubspec_content | Where-Object { $_ -like '*version:*' }
          $pubspec_version = $pubspec_version_line.Split(':')[1].Trim()
          echo "pubspecVersion: $pubspec_version"

          if [ "$tag_version" = "$pubspec_version" ]; then
            echo "版本号一致"
          else
            echo "版本号不一致！请检查!"
            exit 1
          fi

      - name: 打包 win & apk
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - run: flutter build apk --split-per-abi

      - name: 压缩打包文件夹
        run: |
          Compress-Archive -Path ./build/windows/x64/runner/Release -DestinationPath ./bbmusic-windows.zip

      - name: 推送到 release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./bbmusic-windows.zip
            ./build/app/outputs/flutter-apk/*
          token: ${{ secrets.GITHUB_TOKEN }}
