name: 构建 MacOS 应用

on:
  push:
    tags:
      - 'v*'
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Version tag'
  #       required: true
  #       default: '0.0.1'

jobs:
  main:
    name: Release MacOS App
    runs-on: macos-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build macos
      - name: 压缩打包文件夹
        run: |
          tar -zcvf bbmusic-linux.tar.gz ./build/linux/x64/release

      - name: 推送到 release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./bbmusic-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
