name: 构建 Windows 和 Android 应用

on:
  push:
    tags:
      - 'v*'
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Version tag'
  #       required: true
  #       default: 'v0.0.1'

jobs:
  main:
    name: Release Windows App
    runs-on: windows-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 获取 Tag 的 version
        id: get_tag_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          CLEANED_TAG=$(echo "$TAG" | sed 's/^v//')
          echo "$CLEANED_TAG"

      - name: 获取 pubspec.yaml 的 version
        id: get_pubspec_version
        run: |
          $content = Get-Content pubspec.yaml
          $versionLine = $content | Where-Object { $_ -like '*version:*' }
          $version = $versionLine.Split(':')[1].Trim()
          echo "$version"

      - name: 对比 Tag 和 pubspec.yaml 的 version, 确保一致
        run: |
          tag_version=${{ steps.get_tag_version.outputs.tag_version }}
          pubspec_version=${{ steps.get_pubspec_version.outputs.stdout }}
          if [ "$tag_version" = "$pubspec_version" ]; then
            echo "Versions match."
          else
            echo "版本号不一致！请检查!"
            exit 1
          fi

      - name: 打包 win & apk
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - run: flutter build apk --split-per-abi

      - name: 压缩打包文件夹
        run: |
          Compress-Archive -Path ./build/windows/x64/runner/Release -DestinationPath ./bbmusic-windows.zip

      - name: 推送到 release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./bbmusic-windows.zip
            ./build/app/outputs/flutter-apk/*
          token: ${{ secrets.GITHUB_TOKEN }}
