name: 构建 Windows 应用

on:
  push:
    tags:
      - 'v*'
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Version tag'
  #       required: true
  #       default: 'v0.0.1'

jobs:
  main:
    name: Release Windows App
    runs-on: windows-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build windows

      - name: 压缩打包文件夹
        run: |
          Compress-Archive -Path ./build/windows/x64/runner/Release -DestinationPath ./bbmusic-windows.zip

      - name: 推送到 release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./bbmusic-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
